/**
 ******************************************************************************
 * @file    GpioIf_Cfg.h
 * @author  Bernhard Berger
 * @version V1.0.0
 * @date    05.12.2014
 * @brief   Configuration for GpioIf module.
 *
 * Copyright (c) FH OÖ Forschungs und Entwicklungs GmbH, thermocollect
 * You may not use or copy this file except with written permission of the owners.
 ******************************************************************************
 */

#ifndef GPIOIF_CFG_H
#define GPIOIF_CFG_H

/***********************
 * General
 **********************/

/* Number of ports */
#define GPIOIF_NUMBER_OF_PORTS              4u

/***********************
 * Port A
 **********************/

/* Port A configuration */
#define GPIOIF_PORTA_PORT_USED              FALSE
#define GPIOIF_PORTA_REGISTERS              GPIOA
#define GPIOIF_PORTA_CLOCK_DOMAIN           RCC_AHBPeriph_GPIOA

/* Port A / Pin 0 */
#define GPIOIF_PORTA_PIN00_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN00_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN00_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN00_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN00_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN00_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN00_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN00_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTA_PIN00_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN00_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 1 */
#define GPIOIF_PORTA_PIN01_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN01_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN01_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN01_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN01_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN01_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN01_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN01_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTA_PIN01_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN01_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 2 */
#define GPIOIF_PORTA_PIN02_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN02_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN02_SPEED            GPIO_Speed_50MHz
#define GPIOIF_PORTA_PIN02_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN02_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN02_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN02_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN02_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTA_PIN02_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN02_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 3 */
#define GPIOIF_PORTA_PIN03_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN03_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN03_SPEED            GPIO_Speed_50MHz
#define GPIOIF_PORTA_PIN03_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN03_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN03_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN03_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN03_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTA_PIN03_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN03_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 4 */
#define GPIOIF_PORTA_PIN04_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN04_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN04_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN04_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN04_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN04_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN04_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN04_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN04_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN04_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 5 */
#define GPIOIF_PORTA_PIN05_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN05_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN05_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN05_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN05_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN05_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN05_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN05_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN05_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN05_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 6 */
#define GPIOIF_PORTA_PIN06_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN06_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN06_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN06_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN06_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN06_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN06_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN06_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN06_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN06_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 7 */
#define GPIOIF_PORTA_PIN07_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN07_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN07_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN07_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN07_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN07_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN07_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN07_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN07_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN07_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 8 */
#define GPIOIF_PORTA_PIN08_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN08_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN08_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN08_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN08_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN08_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN08_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN08_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN08_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN08_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 9 */
#define GPIOIF_PORTA_PIN09_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN09_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN09_SPEED            GPIO_Speed_50MHz
#define GPIOIF_PORTA_PIN09_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN09_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN09_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN09_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN09_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN09_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN09_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 10 */
#define GPIOIF_PORTA_PIN10_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN10_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN10_SPEED            GPIO_Speed_50MHz
#define GPIOIF_PORTA_PIN10_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN10_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN10_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN10_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN10_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN10_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN10_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 11 */
#define GPIOIF_PORTA_PIN11_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN11_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN11_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN11_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN11_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN11_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN11_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN11_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN11_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN11_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 12 */
#define GPIOIF_PORTA_PIN12_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN12_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN12_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN12_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN12_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN12_ALTERNATE_FUNC   GPIO_AF_1
#define GPIOIF_PORTA_PIN12_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN12_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN12_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN12_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 13 */
#define GPIOIF_PORTA_PIN13_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN13_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN13_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN13_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN13_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN13_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN13_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN13_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN13_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN13_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 14 */
#define GPIOIF_PORTA_PIN14_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN14_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN14_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN14_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN14_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN14_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN14_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN14_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN14_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN14_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port A / Pin 15 */
#define GPIOIF_PORTA_PIN15_CHANNEL_USED     FALSE
#define GPIOIF_PORTA_PIN15_MODE             GPIO_Mode_IN
#define GPIOIF_PORTA_PIN15_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTA_PIN15_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTA_PIN15_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTA_PIN15_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTA_PIN15_ISR_USED         FALSE
#define GPIOIF_PORTA_PIN15_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTA_PIN15_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTA_PIN15_INTERRUPT_TRIG   EXTI_Trigger_Rising

/***********************
 * Port B
 **********************/

/* Port B configuration */
#define GPIOIF_PORTB_PORT_USED              FALSE
#define GPIOIF_PORTB_REGISTERS              GPIOB
#define GPIOIF_PORTB_CLOCK_DOMAIN           RCC_AHBPeriph_GPIOB

/* Port B / Pin 0 */
#define GPIOIF_PORTB_PIN00_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN00_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN00_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN00_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN00_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN00_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN00_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN00_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTB_PIN00_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN00_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 1 */
#define GPIOIF_PORTB_PIN01_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN01_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN01_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN01_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN01_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN01_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN01_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN01_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTB_PIN01_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN01_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 2 */
#define GPIOIF_PORTB_PIN02_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN02_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN02_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN02_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN02_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN02_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN02_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN02_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTB_PIN02_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN02_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 3 */
#define GPIOIF_PORTB_PIN03_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN03_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN03_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN03_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN03_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN03_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN03_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN03_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTB_PIN03_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN03_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 4 */
#define GPIOIF_PORTB_PIN04_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN04_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN04_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN04_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN04_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN04_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN04_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN04_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN04_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN04_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 5 */
#define GPIOIF_PORTB_PIN05_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN05_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN05_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN05_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN05_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN05_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN05_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN05_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN05_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN05_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 6 */
#define GPIOIF_PORTB_PIN06_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN06_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN06_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN06_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN06_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN06_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN06_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN06_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN06_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN06_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 7 */
#define GPIOIF_PORTB_PIN07_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN07_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN07_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN07_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN07_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN07_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN07_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN07_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN07_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN07_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 8 */
#define GPIOIF_PORTB_PIN08_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN08_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN08_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN08_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN08_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN08_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN08_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN08_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN08_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN08_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 9 */
#define GPIOIF_PORTB_PIN09_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN09_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN09_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN09_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN09_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN09_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN09_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN09_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN09_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN09_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 10 */
#define GPIOIF_PORTB_PIN10_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN10_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN10_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN10_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN10_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN10_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN10_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN10_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN10_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN10_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 11 */
#define GPIOIF_PORTB_PIN11_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN11_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN11_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN11_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN11_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN11_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN11_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN11_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN11_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN11_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 12 */
#define GPIOIF_PORTB_PIN12_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN12_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN12_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN12_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN12_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN12_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN12_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN12_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN12_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN12_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 13 */
#define GPIOIF_PORTB_PIN13_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN13_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN13_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN13_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN13_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN13_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN13_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN13_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN13_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN13_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 14 */
#define GPIOIF_PORTB_PIN14_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN14_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN14_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN14_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN14_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN14_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN14_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN14_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN14_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN14_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port B / Pin 15 */
#define GPIOIF_PORTB_PIN15_CHANNEL_USED     FALSE
#define GPIOIF_PORTB_PIN15_MODE             GPIO_Mode_IN
#define GPIOIF_PORTB_PIN15_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTB_PIN15_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTB_PIN15_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTB_PIN15_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTB_PIN15_ISR_USED         FALSE
#define GPIOIF_PORTB_PIN15_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTB_PIN15_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTB_PIN15_INTERRUPT_TRIG   EXTI_Trigger_Rising

/***********************
 * Port C
 **********************/

/* Port C configuration */
#define GPIOIF_PORTC_PORT_USED              FALSE
#define GPIOIF_PORTC_REGISTERS              GPIOC
#define GPIOIF_PORTC_CLOCK_DOMAIN           RCC_AHBPeriph_GPIOC

/* Port C / Pin 0 */
#define GPIOIF_PORTC_PIN00_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN00_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN00_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN00_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN00_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN00_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN00_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN00_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTC_PIN00_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN00_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 1 */
#define GPIOIF_PORTC_PIN01_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN01_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN01_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN01_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN01_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN01_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN01_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN01_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTC_PIN01_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN01_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 2 */
#define GPIOIF_PORTC_PIN02_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN02_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN02_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN02_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN02_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN02_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN02_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN02_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTC_PIN02_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN02_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 3 */
#define GPIOIF_PORTC_PIN03_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN03_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN03_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN03_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN03_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN03_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN03_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN03_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTC_PIN03_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN03_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 4 */
#define GPIOIF_PORTC_PIN04_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN04_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN04_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN04_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN04_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN04_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN04_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN04_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN04_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN04_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 5 */
#define GPIOIF_PORTC_PIN05_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN05_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN05_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN05_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN05_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN05_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN05_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN05_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN05_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN05_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 6 */
#define GPIOIF_PORTC_PIN06_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN06_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN06_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN06_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN06_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN06_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN06_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN06_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN06_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN06_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 7 */
#define GPIOIF_PORTC_PIN07_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN07_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN07_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN07_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN07_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN07_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN07_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN07_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN07_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN07_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 8 */
#define GPIOIF_PORTC_PIN08_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN08_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN08_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN08_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN08_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN08_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN08_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN08_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN08_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN08_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 9 */
#define GPIOIF_PORTC_PIN09_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN09_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN09_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN09_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN09_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN09_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN09_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN09_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN09_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN09_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 10 */
#define GPIOIF_PORTC_PIN10_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN10_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN10_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN10_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN10_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN10_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN10_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN10_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN10_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN10_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 11 */
#define GPIOIF_PORTC_PIN11_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN11_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN11_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN11_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN11_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN11_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN11_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN11_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN11_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN11_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 12 */
#define GPIOIF_PORTC_PIN12_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN12_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN12_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN12_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN12_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN12_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN12_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN12_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN12_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN12_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 13 */
#define GPIOIF_PORTC_PIN13_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN13_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN13_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN13_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN13_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN13_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN13_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN13_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN13_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN13_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 14 */
#define GPIOIF_PORTC_PIN14_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN14_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN14_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN14_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN14_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN14_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN14_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN14_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN14_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN14_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port C / Pin 15 */
#define GPIOIF_PORTC_PIN15_CHANNEL_USED     FALSE
#define GPIOIF_PORTC_PIN15_MODE             GPIO_Mode_IN
#define GPIOIF_PORTC_PIN15_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTC_PIN15_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTC_PIN15_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTC_PIN15_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTC_PIN15_ISR_USED         FALSE
#define GPIOIF_PORTC_PIN15_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTC_PIN15_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTC_PIN15_INTERRUPT_TRIG   EXTI_Trigger_Rising

/***********************
 * Port D
 **********************/

/* Port D configuration */
#define GPIOIF_PORTD_PORT_USED              FALSE
#define GPIOIF_PORTD_REGISTERS              GPIOD
#define GPIOIF_PORTD_CLOCK_DOMAIN           RCC_AHBPeriph_GPIOD

/* Port D / Pin 0 */
#define GPIOIF_PORTD_PIN00_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN00_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN00_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN00_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN00_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN00_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN00_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN00_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTD_PIN00_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN00_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 1 */
#define GPIOIF_PORTD_PIN01_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN01_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN01_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN01_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN01_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN01_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN01_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN01_NVIC_IRQ         EXTI0_1_IRQn
#define GPIOIF_PORTD_PIN01_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN01_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 2 */
#define GPIOIF_PORTD_PIN02_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN02_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN02_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN02_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN02_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN02_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN02_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN02_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTD_PIN02_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN02_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 3 */
#define GPIOIF_PORTD_PIN03_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN03_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN03_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN03_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN03_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN03_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN03_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN03_NVIC_IRQ         EXTI2_3_IRQn
#define GPIOIF_PORTD_PIN03_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN03_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 4 */
#define GPIOIF_PORTD_PIN04_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN04_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN04_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN04_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN04_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN04_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN04_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN04_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN04_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN04_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 5 */
#define GPIOIF_PORTD_PIN05_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN05_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN05_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN05_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN05_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN05_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN05_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN05_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN05_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN05_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 6 */
#define GPIOIF_PORTD_PIN06_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN06_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN06_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN06_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN06_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN06_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN06_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN06_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN06_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN06_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 7 */
#define GPIOIF_PORTD_PIN07_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN07_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN07_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN07_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN07_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN07_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN07_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN07_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN07_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN07_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 8 */
#define GPIOIF_PORTD_PIN08_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN08_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN08_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN08_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN08_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN08_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN08_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN08_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN08_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN08_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 9 */
#define GPIOIF_PORTD_PIN09_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN09_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN09_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN09_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN09_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN09_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN09_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN09_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN09_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN09_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 10 */
#define GPIOIF_PORTD_PIN10_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN10_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN10_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN10_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN10_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN10_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN10_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN10_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN10_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN10_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 11 */
#define GPIOIF_PORTD_PIN11_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN11_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN11_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN11_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN11_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN11_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN11_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN11_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN11_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN11_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 12 */
#define GPIOIF_PORTD_PIN12_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN12_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN12_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN12_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN12_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN12_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN12_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN12_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN12_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN12_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 13 */
#define GPIOIF_PORTD_PIN13_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN13_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN13_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN13_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN13_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN13_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN13_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN13_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN13_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN13_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 14 */
#define GPIOIF_PORTD_PIN14_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN14_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN14_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN14_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN14_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN14_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN14_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN14_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN14_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN14_INTERRUPT_TRIG   EXTI_Trigger_Rising

/* Port D / Pin 15 */
#define GPIOIF_PORTD_PIN15_CHANNEL_USED     FALSE
#define GPIOIF_PORTD_PIN15_MODE             GPIO_Mode_IN
#define GPIOIF_PORTD_PIN15_SPEED            GPIO_Speed_2MHz
#define GPIOIF_PORTD_PIN15_OUTPUT_TYPE      GPIO_OType_PP
#define GPIOIF_PORTD_PIN15_PUD_TYPE         GPIO_PuPd_NOPULL
#define GPIOIF_PORTD_PIN15_ALTERNATE_FUNC   GPIO_AF_0
#define GPIOIF_PORTD_PIN15_ISR_USED         FALSE
#define GPIOIF_PORTD_PIN15_NVIC_IRQ         EXTI4_15_IRQn
#define GPIOIF_PORTD_PIN15_ISR_CALLBACK     NULL_PTR
#define GPIOIF_PORTD_PIN15_INTERRUPT_TRIG   EXTI_Trigger_Rising

#endif /* GPIOIF_CFG_H */
