/**
 ******************************************************************************
 * @file    GpioIf_Cfg.c
 * @author  Bernhard Berger
 * @version V1.0.0
 * @date    05.12.2014
 * @brief   Configuration for GpioIf module.
 *
 * Copyright (c) FH OÖ Forschungs und Entwicklungs GmbH, thermocollect
 * You may not use or copy this file except with written permission of the owners.
 ******************************************************************************
 */

#include "GpioIf.h"
#include "GpioIf_Cfg.h"

/* Clocks */
#include "stm32f0xx_rcc.h"

/****************************************************************
 * Type definitions
 ***************************************************************/

/****************************************************************
 * Macros
 ***************************************************************/

/****************************************************************
 * Function declarations
 ***************************************************************/

/****************************************************************
 * Global variables
 ***************************************************************/

static const GpioIf_PinConfigType GpioIf_pinConfigsPortA[GPIOIF_NUMBER_OF_PINS_PER_CHANNEL] =
{
  /* Pin 0 */
  {
    GPIOIF_PORTA_PIN00_CHANNEL_USED,
    GPIOIF_PORTA_PIN00_MODE,
    GPIOIF_PORTA_PIN00_SPEED,
    GPIOIF_PORTA_PIN00_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN00_PUD_TYPE,
    GPIOIF_PORTA_PIN00_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN00_ISR_USED,
    GPIOIF_PORTA_PIN00_NVIC_IRQ,
    GPIOIF_PORTA_PIN00_ISR_CALLBACK,
    GPIOIF_PORTA_PIN00_INTERRUPT_TRIG
  },
  /* Pin 1 */
  {
    GPIOIF_PORTA_PIN01_CHANNEL_USED,
    GPIOIF_PORTA_PIN01_MODE,
    GPIOIF_PORTA_PIN01_SPEED,
    GPIOIF_PORTA_PIN01_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN01_PUD_TYPE,
    GPIOIF_PORTA_PIN01_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN01_ISR_USED,
    GPIOIF_PORTA_PIN01_NVIC_IRQ,
    GPIOIF_PORTA_PIN01_ISR_CALLBACK,
    GPIOIF_PORTA_PIN01_INTERRUPT_TRIG
  },
  /* Pin 2 */
  {
    GPIOIF_PORTA_PIN02_CHANNEL_USED,
    GPIOIF_PORTA_PIN02_MODE,
    GPIOIF_PORTA_PIN02_SPEED,
    GPIOIF_PORTA_PIN02_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN02_PUD_TYPE,
    GPIOIF_PORTA_PIN02_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN02_ISR_USED,
    GPIOIF_PORTA_PIN02_NVIC_IRQ,
    GPIOIF_PORTA_PIN02_ISR_CALLBACK,
    GPIOIF_PORTA_PIN02_INTERRUPT_TRIG
  },
  /* Pin 3 */
  {
    GPIOIF_PORTA_PIN03_CHANNEL_USED,
    GPIOIF_PORTA_PIN03_MODE,
    GPIOIF_PORTA_PIN03_SPEED,
    GPIOIF_PORTA_PIN03_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN03_PUD_TYPE,
    GPIOIF_PORTA_PIN03_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN03_ISR_USED,
    GPIOIF_PORTA_PIN03_NVIC_IRQ,
    GPIOIF_PORTA_PIN03_ISR_CALLBACK,
    GPIOIF_PORTA_PIN03_INTERRUPT_TRIG
  },
  /* Pin 4 */
  {
    GPIOIF_PORTA_PIN04_CHANNEL_USED,
    GPIOIF_PORTA_PIN04_MODE,
    GPIOIF_PORTA_PIN04_SPEED,
    GPIOIF_PORTA_PIN04_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN04_PUD_TYPE,
    GPIOIF_PORTA_PIN04_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN04_ISR_USED,
    GPIOIF_PORTA_PIN04_NVIC_IRQ,
    GPIOIF_PORTA_PIN04_ISR_CALLBACK,
    GPIOIF_PORTA_PIN04_INTERRUPT_TRIG
  },
  /* Pin 5 */
  {
    GPIOIF_PORTA_PIN05_CHANNEL_USED,
    GPIOIF_PORTA_PIN05_MODE,
    GPIOIF_PORTA_PIN05_SPEED,
    GPIOIF_PORTA_PIN05_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN05_PUD_TYPE,
    GPIOIF_PORTA_PIN05_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN05_ISR_USED,
    GPIOIF_PORTA_PIN05_NVIC_IRQ,
    GPIOIF_PORTA_PIN05_ISR_CALLBACK,
    GPIOIF_PORTA_PIN05_INTERRUPT_TRIG
  },
  /* Pin 6 */
  {
    GPIOIF_PORTA_PIN06_CHANNEL_USED,
    GPIOIF_PORTA_PIN06_MODE,
    GPIOIF_PORTA_PIN06_SPEED,
    GPIOIF_PORTA_PIN06_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN06_PUD_TYPE,
    GPIOIF_PORTA_PIN06_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN06_ISR_USED,
    GPIOIF_PORTA_PIN06_NVIC_IRQ,
    GPIOIF_PORTA_PIN06_ISR_CALLBACK,
    GPIOIF_PORTA_PIN06_INTERRUPT_TRIG
  },
  /* Pin 7 */
  {
    GPIOIF_PORTA_PIN07_CHANNEL_USED,
    GPIOIF_PORTA_PIN07_MODE,
    GPIOIF_PORTA_PIN07_SPEED,
    GPIOIF_PORTA_PIN07_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN07_PUD_TYPE,
    GPIOIF_PORTA_PIN07_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN07_ISR_USED,
    GPIOIF_PORTA_PIN07_NVIC_IRQ,
    GPIOIF_PORTA_PIN07_ISR_CALLBACK,
    GPIOIF_PORTA_PIN07_INTERRUPT_TRIG
  },
  /* Pin 8 */
  {
    GPIOIF_PORTA_PIN08_CHANNEL_USED,
    GPIOIF_PORTA_PIN08_MODE,
    GPIOIF_PORTA_PIN08_SPEED,
    GPIOIF_PORTA_PIN08_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN08_PUD_TYPE,
    GPIOIF_PORTA_PIN08_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN08_ISR_USED,
    GPIOIF_PORTA_PIN08_NVIC_IRQ,
    GPIOIF_PORTA_PIN08_ISR_CALLBACK,
    GPIOIF_PORTA_PIN08_INTERRUPT_TRIG
  },
  /* Pin 9 */
  {
    GPIOIF_PORTA_PIN09_CHANNEL_USED,
    GPIOIF_PORTA_PIN09_MODE,
    GPIOIF_PORTA_PIN09_SPEED,
    GPIOIF_PORTA_PIN09_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN09_PUD_TYPE,
    GPIOIF_PORTA_PIN09_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN09_ISR_USED,
    GPIOIF_PORTA_PIN09_NVIC_IRQ,
    GPIOIF_PORTA_PIN09_ISR_CALLBACK,
    GPIOIF_PORTA_PIN09_INTERRUPT_TRIG
  },
  /* Pin 10 */
  {
    GPIOIF_PORTA_PIN10_CHANNEL_USED,
    GPIOIF_PORTA_PIN10_MODE,
    GPIOIF_PORTA_PIN10_SPEED,
    GPIOIF_PORTA_PIN10_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN10_PUD_TYPE,
    GPIOIF_PORTA_PIN10_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN10_ISR_USED,
    GPIOIF_PORTA_PIN10_NVIC_IRQ,
    GPIOIF_PORTA_PIN10_ISR_CALLBACK,
    GPIOIF_PORTA_PIN10_INTERRUPT_TRIG
  },
  /* Pin 11 */
  {
    GPIOIF_PORTA_PIN11_CHANNEL_USED,
    GPIOIF_PORTA_PIN11_MODE,
    GPIOIF_PORTA_PIN11_SPEED,
    GPIOIF_PORTA_PIN11_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN11_PUD_TYPE,
    GPIOIF_PORTA_PIN11_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN11_ISR_USED,
    GPIOIF_PORTA_PIN11_NVIC_IRQ,
    GPIOIF_PORTA_PIN11_ISR_CALLBACK,
    GPIOIF_PORTA_PIN11_INTERRUPT_TRIG
  },
  /* Pin 12 */
  {
    GPIOIF_PORTA_PIN12_CHANNEL_USED,
    GPIOIF_PORTA_PIN12_MODE,
    GPIOIF_PORTA_PIN12_SPEED,
    GPIOIF_PORTA_PIN12_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN12_PUD_TYPE,
    GPIOIF_PORTA_PIN12_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN12_ISR_USED,
    GPIOIF_PORTA_PIN12_NVIC_IRQ,
    GPIOIF_PORTA_PIN12_ISR_CALLBACK,
    GPIOIF_PORTA_PIN12_INTERRUPT_TRIG
  },
  /* Pin 13 */
  {
    GPIOIF_PORTA_PIN13_CHANNEL_USED,
    GPIOIF_PORTA_PIN13_MODE,
    GPIOIF_PORTA_PIN13_SPEED,
    GPIOIF_PORTA_PIN13_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN13_PUD_TYPE,
    GPIOIF_PORTA_PIN13_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN13_ISR_USED,
    GPIOIF_PORTA_PIN13_NVIC_IRQ,
    GPIOIF_PORTA_PIN13_ISR_CALLBACK,
    GPIOIF_PORTA_PIN13_INTERRUPT_TRIG
  },
  /* Pin 14 */
  {
    GPIOIF_PORTA_PIN14_CHANNEL_USED,
    GPIOIF_PORTA_PIN14_MODE,
    GPIOIF_PORTA_PIN14_SPEED,
    GPIOIF_PORTA_PIN14_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN14_PUD_TYPE,
    GPIOIF_PORTA_PIN14_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN14_ISR_USED,
    GPIOIF_PORTA_PIN14_NVIC_IRQ,
    GPIOIF_PORTA_PIN14_ISR_CALLBACK,
    GPIOIF_PORTA_PIN14_INTERRUPT_TRIG
  },
  /* Pin 15 */
  {
    GPIOIF_PORTA_PIN15_CHANNEL_USED,
    GPIOIF_PORTA_PIN15_MODE,
    GPIOIF_PORTA_PIN15_SPEED,
    GPIOIF_PORTA_PIN15_OUTPUT_TYPE,
    GPIOIF_PORTA_PIN15_PUD_TYPE,
    GPIOIF_PORTA_PIN15_ALTERNATE_FUNC,	
    GPIOIF_PORTA_PIN15_ISR_USED,
    GPIOIF_PORTA_PIN15_NVIC_IRQ,
    GPIOIF_PORTA_PIN15_ISR_CALLBACK,
    GPIOIF_PORTA_PIN15_INTERRUPT_TRIG
  }
};

static const GpioIf_PinConfigType GpioIf_pinConfigsPortB[GPIOIF_NUMBER_OF_PINS_PER_CHANNEL] =
{
  /* Pin 0 */
  {
    GPIOIF_PORTB_PIN00_CHANNEL_USED,
    GPIOIF_PORTB_PIN00_MODE,
    GPIOIF_PORTB_PIN00_SPEED,
    GPIOIF_PORTB_PIN00_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN00_PUD_TYPE,
    GPIOIF_PORTB_PIN00_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN00_ISR_USED,
    GPIOIF_PORTB_PIN00_NVIC_IRQ,
    GPIOIF_PORTB_PIN00_ISR_CALLBACK,
    GPIOIF_PORTB_PIN00_INTERRUPT_TRIG
  },
  /* Pin 1 */
  {
    GPIOIF_PORTB_PIN01_CHANNEL_USED,
    GPIOIF_PORTB_PIN01_MODE,
    GPIOIF_PORTB_PIN01_SPEED,
    GPIOIF_PORTB_PIN01_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN01_PUD_TYPE,
    GPIOIF_PORTB_PIN01_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN01_ISR_USED,
    GPIOIF_PORTB_PIN01_NVIC_IRQ,
    GPIOIF_PORTB_PIN01_ISR_CALLBACK,
    GPIOIF_PORTB_PIN01_INTERRUPT_TRIG
  },
  /* Pin 2 */
  {
    GPIOIF_PORTB_PIN02_CHANNEL_USED,
    GPIOIF_PORTB_PIN02_MODE,
    GPIOIF_PORTB_PIN02_SPEED,
    GPIOIF_PORTB_PIN02_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN02_PUD_TYPE,
    GPIOIF_PORTB_PIN02_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN02_ISR_USED,
    GPIOIF_PORTB_PIN02_NVIC_IRQ,
    GPIOIF_PORTB_PIN02_ISR_CALLBACK,
    GPIOIF_PORTB_PIN02_INTERRUPT_TRIG
  },
  /* Pin 3 */
  {
    GPIOIF_PORTB_PIN03_CHANNEL_USED,
    GPIOIF_PORTB_PIN03_MODE,
    GPIOIF_PORTB_PIN03_SPEED,
    GPIOIF_PORTB_PIN03_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN03_PUD_TYPE,
    GPIOIF_PORTB_PIN03_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN03_ISR_USED,
    GPIOIF_PORTB_PIN03_NVIC_IRQ,
    GPIOIF_PORTB_PIN03_ISR_CALLBACK,
    GPIOIF_PORTB_PIN03_INTERRUPT_TRIG
  },
  /* Pin 4 */
  {
    GPIOIF_PORTB_PIN04_CHANNEL_USED,
    GPIOIF_PORTB_PIN04_MODE,
    GPIOIF_PORTB_PIN04_SPEED,
    GPIOIF_PORTB_PIN04_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN04_PUD_TYPE,
    GPIOIF_PORTB_PIN04_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN04_ISR_USED,
    GPIOIF_PORTB_PIN04_NVIC_IRQ,
    GPIOIF_PORTB_PIN04_ISR_CALLBACK,
    GPIOIF_PORTB_PIN04_INTERRUPT_TRIG
  },
  /* Pin 5 */
  {
    GPIOIF_PORTB_PIN05_CHANNEL_USED,
    GPIOIF_PORTB_PIN05_MODE,
    GPIOIF_PORTB_PIN05_SPEED,
    GPIOIF_PORTB_PIN05_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN05_PUD_TYPE,
    GPIOIF_PORTB_PIN05_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN05_ISR_USED,
    GPIOIF_PORTB_PIN05_NVIC_IRQ,
    GPIOIF_PORTB_PIN05_ISR_CALLBACK,
    GPIOIF_PORTB_PIN05_INTERRUPT_TRIG
  },
  /* Pin 6 */
  {
    GPIOIF_PORTB_PIN06_CHANNEL_USED,
    GPIOIF_PORTB_PIN06_MODE,
    GPIOIF_PORTB_PIN06_SPEED,
    GPIOIF_PORTB_PIN06_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN06_PUD_TYPE,
    GPIOIF_PORTB_PIN06_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN06_ISR_USED,
    GPIOIF_PORTB_PIN06_NVIC_IRQ,
    GPIOIF_PORTB_PIN06_ISR_CALLBACK,
    GPIOIF_PORTB_PIN06_INTERRUPT_TRIG
  },
  /* Pin 7 */
  {
    GPIOIF_PORTB_PIN07_CHANNEL_USED,
    GPIOIF_PORTB_PIN07_MODE,
    GPIOIF_PORTB_PIN07_SPEED,
    GPIOIF_PORTB_PIN07_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN07_PUD_TYPE,
    GPIOIF_PORTB_PIN07_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN07_ISR_USED,
    GPIOIF_PORTB_PIN07_NVIC_IRQ,
    GPIOIF_PORTB_PIN07_ISR_CALLBACK,
    GPIOIF_PORTB_PIN07_INTERRUPT_TRIG
  },
  /* Pin 8 */
  {
    GPIOIF_PORTB_PIN08_CHANNEL_USED,
    GPIOIF_PORTB_PIN08_MODE,
    GPIOIF_PORTB_PIN08_SPEED,
    GPIOIF_PORTB_PIN08_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN08_PUD_TYPE,
    GPIOIF_PORTB_PIN08_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN08_ISR_USED,
    GPIOIF_PORTB_PIN08_NVIC_IRQ,
    GPIOIF_PORTB_PIN08_ISR_CALLBACK,
    GPIOIF_PORTB_PIN08_INTERRUPT_TRIG
  },
  /* Pin 9 */
  {
    GPIOIF_PORTB_PIN09_CHANNEL_USED,
    GPIOIF_PORTB_PIN09_MODE,
    GPIOIF_PORTB_PIN09_SPEED,
    GPIOIF_PORTB_PIN09_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN09_PUD_TYPE,
    GPIOIF_PORTB_PIN09_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN09_ISR_USED,
    GPIOIF_PORTB_PIN09_NVIC_IRQ,
    GPIOIF_PORTB_PIN09_ISR_CALLBACK,
    GPIOIF_PORTB_PIN09_INTERRUPT_TRIG
  },
  /* Pin 10 */
  {
    GPIOIF_PORTB_PIN10_CHANNEL_USED,
    GPIOIF_PORTB_PIN10_MODE,
    GPIOIF_PORTB_PIN10_SPEED,
    GPIOIF_PORTB_PIN10_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN10_PUD_TYPE,
    GPIOIF_PORTB_PIN10_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN10_ISR_USED,
    GPIOIF_PORTB_PIN10_NVIC_IRQ,
    GPIOIF_PORTB_PIN10_ISR_CALLBACK,
    GPIOIF_PORTB_PIN10_INTERRUPT_TRIG
  },
  /* Pin 11 */
  {
    GPIOIF_PORTB_PIN11_CHANNEL_USED,
    GPIOIF_PORTB_PIN11_MODE,
    GPIOIF_PORTB_PIN11_SPEED,
    GPIOIF_PORTB_PIN11_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN11_PUD_TYPE,
    GPIOIF_PORTB_PIN11_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN11_ISR_USED,
    GPIOIF_PORTB_PIN11_NVIC_IRQ,
    GPIOIF_PORTB_PIN11_ISR_CALLBACK,
    GPIOIF_PORTB_PIN11_INTERRUPT_TRIG
  },
  /* Pin 12 */
  {
    GPIOIF_PORTB_PIN12_CHANNEL_USED,
    GPIOIF_PORTB_PIN12_MODE,
    GPIOIF_PORTB_PIN12_SPEED,
    GPIOIF_PORTB_PIN12_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN12_PUD_TYPE,
    GPIOIF_PORTB_PIN12_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN12_ISR_USED,
    GPIOIF_PORTB_PIN12_NVIC_IRQ,
    GPIOIF_PORTB_PIN12_ISR_CALLBACK,
    GPIOIF_PORTB_PIN12_INTERRUPT_TRIG
  },
  /* Pin 13 */
  {
    GPIOIF_PORTB_PIN13_CHANNEL_USED,
    GPIOIF_PORTB_PIN13_MODE,
    GPIOIF_PORTB_PIN13_SPEED,
    GPIOIF_PORTB_PIN13_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN13_PUD_TYPE,
    GPIOIF_PORTB_PIN13_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN13_ISR_USED,
    GPIOIF_PORTB_PIN13_NVIC_IRQ,
    GPIOIF_PORTB_PIN13_ISR_CALLBACK,
    GPIOIF_PORTB_PIN13_INTERRUPT_TRIG
  },
  /* Pin 14 */
  {
    GPIOIF_PORTB_PIN14_CHANNEL_USED,
    GPIOIF_PORTB_PIN14_MODE,
    GPIOIF_PORTB_PIN14_SPEED,
    GPIOIF_PORTB_PIN14_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN14_PUD_TYPE,
    GPIOIF_PORTB_PIN14_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN14_ISR_USED,
    GPIOIF_PORTB_PIN14_NVIC_IRQ,
    GPIOIF_PORTB_PIN14_ISR_CALLBACK,
    GPIOIF_PORTB_PIN14_INTERRUPT_TRIG
  },
  /* Pin 15 */
  {
    GPIOIF_PORTB_PIN15_CHANNEL_USED,
    GPIOIF_PORTB_PIN15_MODE,
    GPIOIF_PORTB_PIN15_SPEED,
    GPIOIF_PORTB_PIN15_OUTPUT_TYPE,
    GPIOIF_PORTB_PIN15_PUD_TYPE,
    GPIOIF_PORTB_PIN15_ALTERNATE_FUNC,	
    GPIOIF_PORTB_PIN15_ISR_USED,
    GPIOIF_PORTB_PIN15_NVIC_IRQ,
    GPIOIF_PORTB_PIN15_ISR_CALLBACK,
    GPIOIF_PORTB_PIN15_INTERRUPT_TRIG
  }
};

static const GpioIf_PinConfigType GpioIf_pinConfigsPortC[GPIOIF_NUMBER_OF_PINS_PER_CHANNEL] =
{
  /* Pin 0 */
  {
    GPIOIF_PORTC_PIN00_CHANNEL_USED,
    GPIOIF_PORTC_PIN00_MODE,
    GPIOIF_PORTC_PIN00_SPEED,
    GPIOIF_PORTC_PIN00_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN00_PUD_TYPE,
    GPIOIF_PORTC_PIN00_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN00_ISR_USED,
    GPIOIF_PORTC_PIN00_NVIC_IRQ,
    GPIOIF_PORTC_PIN00_ISR_CALLBACK,
    GPIOIF_PORTC_PIN00_INTERRUPT_TRIG
  },
  /* Pin 1 */
  {
    GPIOIF_PORTC_PIN01_CHANNEL_USED,
    GPIOIF_PORTC_PIN01_MODE,
    GPIOIF_PORTC_PIN01_SPEED,
    GPIOIF_PORTC_PIN01_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN01_PUD_TYPE,
    GPIOIF_PORTC_PIN01_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN01_ISR_USED,
    GPIOIF_PORTC_PIN01_NVIC_IRQ,
    GPIOIF_PORTC_PIN01_ISR_CALLBACK,
    GPIOIF_PORTC_PIN01_INTERRUPT_TRIG
  },
  /* Pin 2 */
  {
    GPIOIF_PORTC_PIN02_CHANNEL_USED,
    GPIOIF_PORTC_PIN02_MODE,
    GPIOIF_PORTC_PIN02_SPEED,
    GPIOIF_PORTC_PIN02_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN02_PUD_TYPE,
    GPIOIF_PORTC_PIN02_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN02_ISR_USED,
    GPIOIF_PORTC_PIN02_NVIC_IRQ,
    GPIOIF_PORTC_PIN02_ISR_CALLBACK,
    GPIOIF_PORTC_PIN02_INTERRUPT_TRIG
  },
  /* Pin 3 */
  {
    GPIOIF_PORTC_PIN03_CHANNEL_USED,
    GPIOIF_PORTC_PIN03_MODE,
    GPIOIF_PORTC_PIN03_SPEED,
    GPIOIF_PORTC_PIN03_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN03_PUD_TYPE,
    GPIOIF_PORTC_PIN03_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN03_ISR_USED,
    GPIOIF_PORTC_PIN03_NVIC_IRQ,
    GPIOIF_PORTC_PIN03_ISR_CALLBACK,
    GPIOIF_PORTC_PIN03_INTERRUPT_TRIG
  },
  /* Pin 4 */
  {
    GPIOIF_PORTC_PIN04_CHANNEL_USED,
    GPIOIF_PORTC_PIN04_MODE,
    GPIOIF_PORTC_PIN04_SPEED,
    GPIOIF_PORTC_PIN04_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN04_PUD_TYPE,
    GPIOIF_PORTC_PIN04_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN04_ISR_USED,
    GPIOIF_PORTC_PIN04_NVIC_IRQ,
    GPIOIF_PORTC_PIN04_ISR_CALLBACK,
    GPIOIF_PORTC_PIN04_INTERRUPT_TRIG
  },
  /* Pin 5 */
  {
    GPIOIF_PORTC_PIN05_CHANNEL_USED,
    GPIOIF_PORTC_PIN05_MODE,
    GPIOIF_PORTC_PIN05_SPEED,
    GPIOIF_PORTC_PIN05_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN05_PUD_TYPE,
    GPIOIF_PORTC_PIN05_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN05_ISR_USED,
    GPIOIF_PORTC_PIN05_NVIC_IRQ,
    GPIOIF_PORTC_PIN05_ISR_CALLBACK,
    GPIOIF_PORTC_PIN05_INTERRUPT_TRIG
  },
  /* Pin 6 */
  {
    GPIOIF_PORTC_PIN06_CHANNEL_USED,
    GPIOIF_PORTC_PIN06_MODE,
    GPIOIF_PORTC_PIN06_SPEED,
    GPIOIF_PORTC_PIN06_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN06_PUD_TYPE,
    GPIOIF_PORTC_PIN06_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN06_ISR_USED,
    GPIOIF_PORTC_PIN06_NVIC_IRQ,
    GPIOIF_PORTC_PIN06_ISR_CALLBACK,
    GPIOIF_PORTC_PIN06_INTERRUPT_TRIG
  },
  /* Pin 7 */
  {
    GPIOIF_PORTC_PIN07_CHANNEL_USED,
    GPIOIF_PORTC_PIN07_MODE,
    GPIOIF_PORTC_PIN07_SPEED,
    GPIOIF_PORTC_PIN07_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN07_PUD_TYPE,
    GPIOIF_PORTC_PIN07_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN07_ISR_USED,
    GPIOIF_PORTC_PIN07_NVIC_IRQ,
    GPIOIF_PORTC_PIN07_ISR_CALLBACK,
    GPIOIF_PORTC_PIN07_INTERRUPT_TRIG
  },
  /* Pin 8 */
  {
    GPIOIF_PORTC_PIN08_CHANNEL_USED,
    GPIOIF_PORTC_PIN08_MODE,
    GPIOIF_PORTC_PIN08_SPEED,
    GPIOIF_PORTC_PIN08_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN08_PUD_TYPE,
    GPIOIF_PORTC_PIN08_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN08_ISR_USED,
    GPIOIF_PORTC_PIN08_NVIC_IRQ,
    GPIOIF_PORTC_PIN08_ISR_CALLBACK,
    GPIOIF_PORTC_PIN08_INTERRUPT_TRIG
  },
  /* Pin 9 */
  {
    GPIOIF_PORTC_PIN09_CHANNEL_USED,
    GPIOIF_PORTC_PIN09_MODE,
    GPIOIF_PORTC_PIN09_SPEED,
    GPIOIF_PORTC_PIN09_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN09_PUD_TYPE,
    GPIOIF_PORTC_PIN09_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN09_ISR_USED,
    GPIOIF_PORTC_PIN09_NVIC_IRQ,
    GPIOIF_PORTC_PIN09_ISR_CALLBACK,
    GPIOIF_PORTC_PIN09_INTERRUPT_TRIG
  },
  /* Pin 10 */
  {
    GPIOIF_PORTC_PIN10_CHANNEL_USED,
    GPIOIF_PORTC_PIN10_MODE,
    GPIOIF_PORTC_PIN10_SPEED,
    GPIOIF_PORTC_PIN10_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN10_PUD_TYPE,
    GPIOIF_PORTC_PIN10_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN10_ISR_USED,
    GPIOIF_PORTC_PIN10_NVIC_IRQ,
    GPIOIF_PORTC_PIN10_ISR_CALLBACK,
    GPIOIF_PORTC_PIN10_INTERRUPT_TRIG
  },
  /* Pin 11 */
  {
    GPIOIF_PORTC_PIN11_CHANNEL_USED,
    GPIOIF_PORTC_PIN11_MODE,
    GPIOIF_PORTC_PIN11_SPEED,
    GPIOIF_PORTC_PIN11_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN11_PUD_TYPE,
    GPIOIF_PORTC_PIN11_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN11_ISR_USED,
    GPIOIF_PORTC_PIN11_NVIC_IRQ,
    GPIOIF_PORTC_PIN11_ISR_CALLBACK,
    GPIOIF_PORTC_PIN11_INTERRUPT_TRIG
  },
  /* Pin 12 */
  {
    GPIOIF_PORTC_PIN12_CHANNEL_USED,
    GPIOIF_PORTC_PIN12_MODE,
    GPIOIF_PORTC_PIN12_SPEED,
    GPIOIF_PORTC_PIN12_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN12_PUD_TYPE,
    GPIOIF_PORTC_PIN12_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN12_ISR_USED,
    GPIOIF_PORTC_PIN12_NVIC_IRQ,
    GPIOIF_PORTC_PIN12_ISR_CALLBACK,
    GPIOIF_PORTC_PIN12_INTERRUPT_TRIG
  },
  /* Pin 13 */
  {
    GPIOIF_PORTC_PIN13_CHANNEL_USED,
    GPIOIF_PORTC_PIN13_MODE,
    GPIOIF_PORTC_PIN13_SPEED,
    GPIOIF_PORTC_PIN13_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN13_PUD_TYPE,
    GPIOIF_PORTC_PIN13_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN13_ISR_USED,
    GPIOIF_PORTC_PIN13_NVIC_IRQ,
    GPIOIF_PORTC_PIN13_ISR_CALLBACK,
    GPIOIF_PORTC_PIN13_INTERRUPT_TRIG
  },
  /* Pin 14 */
  {
    GPIOIF_PORTC_PIN14_CHANNEL_USED,
    GPIOIF_PORTC_PIN14_MODE,
    GPIOIF_PORTC_PIN14_SPEED,
    GPIOIF_PORTC_PIN14_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN14_PUD_TYPE,
    GPIOIF_PORTC_PIN14_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN14_ISR_USED,
    GPIOIF_PORTC_PIN14_NVIC_IRQ,
    GPIOIF_PORTC_PIN14_ISR_CALLBACK,
    GPIOIF_PORTC_PIN14_INTERRUPT_TRIG
  },
  /* Pin 15 */
  {
    GPIOIF_PORTC_PIN15_CHANNEL_USED,
    GPIOIF_PORTC_PIN15_MODE,
    GPIOIF_PORTC_PIN15_SPEED,
    GPIOIF_PORTC_PIN15_OUTPUT_TYPE,
    GPIOIF_PORTC_PIN15_PUD_TYPE,
    GPIOIF_PORTC_PIN15_ALTERNATE_FUNC,	
    GPIOIF_PORTC_PIN15_ISR_USED,
    GPIOIF_PORTC_PIN15_NVIC_IRQ,
    GPIOIF_PORTC_PIN15_ISR_CALLBACK,
    GPIOIF_PORTC_PIN15_INTERRUPT_TRIG
  }
};

static const GpioIf_PinConfigType GpioIf_pinConfigsPortD[GPIOIF_NUMBER_OF_PINS_PER_CHANNEL] =
{
  /* Pin 0 */
  {
    GPIOIF_PORTD_PIN00_CHANNEL_USED,
    GPIOIF_PORTD_PIN00_MODE,
    GPIOIF_PORTD_PIN00_SPEED,
    GPIOIF_PORTD_PIN00_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN00_PUD_TYPE,
    GPIOIF_PORTD_PIN00_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN00_ISR_USED,
    GPIOIF_PORTD_PIN00_NVIC_IRQ,
    GPIOIF_PORTD_PIN00_ISR_CALLBACK,
    GPIOIF_PORTD_PIN00_INTERRUPT_TRIG
  },
  /* Pin 1 */
  {
    GPIOIF_PORTD_PIN01_CHANNEL_USED,
    GPIOIF_PORTD_PIN01_MODE,
    GPIOIF_PORTD_PIN01_SPEED,
    GPIOIF_PORTD_PIN01_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN01_PUD_TYPE,
    GPIOIF_PORTD_PIN01_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN01_ISR_USED,
    GPIOIF_PORTD_PIN01_NVIC_IRQ,
    GPIOIF_PORTD_PIN01_ISR_CALLBACK,
    GPIOIF_PORTD_PIN01_INTERRUPT_TRIG
  },
  /* Pin 2 */
  {
    GPIOIF_PORTD_PIN02_CHANNEL_USED,
    GPIOIF_PORTD_PIN02_MODE,
    GPIOIF_PORTD_PIN02_SPEED,
    GPIOIF_PORTD_PIN02_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN02_PUD_TYPE,
    GPIOIF_PORTD_PIN02_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN02_ISR_USED,
    GPIOIF_PORTD_PIN02_NVIC_IRQ,
    GPIOIF_PORTD_PIN02_ISR_CALLBACK,
    GPIOIF_PORTD_PIN02_INTERRUPT_TRIG
  },
  /* Pin 3 */
  {
    GPIOIF_PORTD_PIN03_CHANNEL_USED,
    GPIOIF_PORTD_PIN03_MODE,
    GPIOIF_PORTD_PIN03_SPEED,
    GPIOIF_PORTD_PIN03_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN03_PUD_TYPE,
    GPIOIF_PORTD_PIN03_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN03_ISR_USED,
    GPIOIF_PORTD_PIN03_NVIC_IRQ,
    GPIOIF_PORTD_PIN03_ISR_CALLBACK,
    GPIOIF_PORTD_PIN03_INTERRUPT_TRIG
  },
  /* Pin 4 */
  {
    GPIOIF_PORTD_PIN04_CHANNEL_USED,
    GPIOIF_PORTD_PIN04_MODE,
    GPIOIF_PORTD_PIN04_SPEED,
    GPIOIF_PORTD_PIN04_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN04_PUD_TYPE,
    GPIOIF_PORTD_PIN04_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN04_ISR_USED,
    GPIOIF_PORTD_PIN04_NVIC_IRQ,
    GPIOIF_PORTD_PIN04_ISR_CALLBACK,
    GPIOIF_PORTD_PIN04_INTERRUPT_TRIG
  },
  /* Pin 5 */
  {
    GPIOIF_PORTD_PIN05_CHANNEL_USED,
    GPIOIF_PORTD_PIN05_MODE,
    GPIOIF_PORTD_PIN05_SPEED,
    GPIOIF_PORTD_PIN05_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN05_PUD_TYPE,
    GPIOIF_PORTD_PIN05_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN05_ISR_USED,
    GPIOIF_PORTD_PIN05_NVIC_IRQ,
    GPIOIF_PORTD_PIN05_ISR_CALLBACK,
    GPIOIF_PORTD_PIN05_INTERRUPT_TRIG
  },
  /* Pin 6 */
  {
    GPIOIF_PORTD_PIN06_CHANNEL_USED,
    GPIOIF_PORTD_PIN06_MODE,
    GPIOIF_PORTD_PIN06_SPEED,
    GPIOIF_PORTD_PIN06_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN06_PUD_TYPE,
    GPIOIF_PORTD_PIN06_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN06_ISR_USED,
    GPIOIF_PORTD_PIN06_NVIC_IRQ,
    GPIOIF_PORTD_PIN06_ISR_CALLBACK,
    GPIOIF_PORTD_PIN06_INTERRUPT_TRIG
  },
  /* Pin 7 */
  {
    GPIOIF_PORTD_PIN07_CHANNEL_USED,
    GPIOIF_PORTD_PIN07_MODE,
    GPIOIF_PORTD_PIN07_SPEED,
    GPIOIF_PORTD_PIN07_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN07_PUD_TYPE,
    GPIOIF_PORTD_PIN07_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN07_ISR_USED,
    GPIOIF_PORTD_PIN07_NVIC_IRQ,
    GPIOIF_PORTD_PIN07_ISR_CALLBACK,
    GPIOIF_PORTD_PIN07_INTERRUPT_TRIG
  },
  /* Pin 8 */
  {
    GPIOIF_PORTD_PIN08_CHANNEL_USED,
    GPIOIF_PORTD_PIN08_MODE,
    GPIOIF_PORTD_PIN08_SPEED,
    GPIOIF_PORTD_PIN08_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN08_PUD_TYPE,
    GPIOIF_PORTD_PIN08_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN08_ISR_USED,
    GPIOIF_PORTD_PIN08_NVIC_IRQ,
    GPIOIF_PORTD_PIN08_ISR_CALLBACK,
    GPIOIF_PORTD_PIN08_INTERRUPT_TRIG
  },
  /* Pin 9 */
  {
    GPIOIF_PORTD_PIN09_CHANNEL_USED,
    GPIOIF_PORTD_PIN09_MODE,
    GPIOIF_PORTD_PIN09_SPEED,
    GPIOIF_PORTD_PIN09_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN09_PUD_TYPE,
    GPIOIF_PORTD_PIN09_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN09_ISR_USED,
    GPIOIF_PORTD_PIN09_NVIC_IRQ,
    GPIOIF_PORTD_PIN09_ISR_CALLBACK,
    GPIOIF_PORTD_PIN09_INTERRUPT_TRIG
  },
  /* Pin 10 */
  {
    GPIOIF_PORTD_PIN10_CHANNEL_USED,
    GPIOIF_PORTD_PIN10_MODE,
    GPIOIF_PORTD_PIN10_SPEED,
    GPIOIF_PORTD_PIN10_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN10_PUD_TYPE,
    GPIOIF_PORTD_PIN10_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN10_ISR_USED,
    GPIOIF_PORTD_PIN10_NVIC_IRQ,
    GPIOIF_PORTD_PIN10_ISR_CALLBACK,
    GPIOIF_PORTD_PIN10_INTERRUPT_TRIG
  },
  /* Pin 11 */
  {
    GPIOIF_PORTD_PIN11_CHANNEL_USED,
    GPIOIF_PORTD_PIN11_MODE,
    GPIOIF_PORTD_PIN11_SPEED,
    GPIOIF_PORTD_PIN11_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN11_PUD_TYPE,
    GPIOIF_PORTD_PIN11_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN11_ISR_USED,
    GPIOIF_PORTD_PIN11_NVIC_IRQ,
    GPIOIF_PORTD_PIN11_ISR_CALLBACK,
    GPIOIF_PORTD_PIN11_INTERRUPT_TRIG
  },
  /* Pin 12 */
  {
    GPIOIF_PORTD_PIN12_CHANNEL_USED,
    GPIOIF_PORTD_PIN12_MODE,
    GPIOIF_PORTD_PIN12_SPEED,
    GPIOIF_PORTD_PIN12_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN12_PUD_TYPE,
    GPIOIF_PORTD_PIN12_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN12_ISR_USED,
    GPIOIF_PORTD_PIN12_NVIC_IRQ,
    GPIOIF_PORTD_PIN12_ISR_CALLBACK,
    GPIOIF_PORTD_PIN12_INTERRUPT_TRIG
  },
  /* Pin 13 */
  {
    GPIOIF_PORTD_PIN13_CHANNEL_USED,
    GPIOIF_PORTD_PIN13_MODE,
    GPIOIF_PORTD_PIN13_SPEED,
    GPIOIF_PORTD_PIN13_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN13_PUD_TYPE,
    GPIOIF_PORTD_PIN13_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN13_ISR_USED,
    GPIOIF_PORTD_PIN13_NVIC_IRQ,
    GPIOIF_PORTD_PIN13_ISR_CALLBACK,
    GPIOIF_PORTD_PIN13_INTERRUPT_TRIG
  },
  /* Pin 14 */
  {
    GPIOIF_PORTD_PIN14_CHANNEL_USED,
    GPIOIF_PORTD_PIN14_MODE,
    GPIOIF_PORTD_PIN14_SPEED,
    GPIOIF_PORTD_PIN14_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN14_PUD_TYPE,
    GPIOIF_PORTD_PIN14_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN14_ISR_USED,
    GPIOIF_PORTD_PIN14_NVIC_IRQ,
    GPIOIF_PORTD_PIN14_ISR_CALLBACK,
    GPIOIF_PORTD_PIN14_INTERRUPT_TRIG
  },
  /* Pin 15 */
  {
    GPIOIF_PORTD_PIN15_CHANNEL_USED,
    GPIOIF_PORTD_PIN15_MODE,
    GPIOIF_PORTD_PIN15_SPEED,
    GPIOIF_PORTD_PIN15_OUTPUT_TYPE,
    GPIOIF_PORTD_PIN15_PUD_TYPE,
    GPIOIF_PORTD_PIN15_ALTERNATE_FUNC,	
    GPIOIF_PORTD_PIN15_ISR_USED,
    GPIOIF_PORTD_PIN15_NVIC_IRQ,
    GPIOIF_PORTD_PIN15_ISR_CALLBACK,
    GPIOIF_PORTD_PIN15_INTERRUPT_TRIG
  }
};

static const GpioIf_PortConfigType GpioIf_portConfigs[GPIOIF_NUMBER_OF_PORTS] =
{
  {
    GPIOIF_PORTA_PORT_USED,
    GPIOIF_NUMBER_OF_PINS_PER_CHANNEL,
    GpioIf_pinConfigsPortA,
    GPIOIF_PORTA_REGISTERS,
    GPIOIF_PORTA_CLOCK_DOMAIN
  },
  {
    GPIOIF_PORTB_PORT_USED,
    GPIOIF_NUMBER_OF_PINS_PER_CHANNEL,
    GpioIf_pinConfigsPortB,
    GPIOIF_PORTB_REGISTERS,
    GPIOIF_PORTB_CLOCK_DOMAIN
  },
  {
    GPIOIF_PORTC_PORT_USED,
    GPIOIF_NUMBER_OF_PINS_PER_CHANNEL,
    GpioIf_pinConfigsPortC,
    GPIOIF_PORTC_REGISTERS,
    GPIOIF_PORTC_CLOCK_DOMAIN
  },
  {
    GPIOIF_PORTD_PORT_USED,
    GPIOIF_NUMBER_OF_PINS_PER_CHANNEL,
    GpioIf_pinConfigsPortD,
    GPIOIF_PORTD_REGISTERS,
    GPIOIF_PORTD_CLOCK_DOMAIN
  }
};

const GpioIf_ConfigType GpioIf_config =
{
  GPIOIF_NUMBER_OF_PORTS,
  GpioIf_portConfigs
};

/****************************************************************
 * User functions
 ***************************************************************/
